export const seedModules = [
  {
    slug: 'ayurveda-basics',
    title: 'Ayurveda Basics',
    description: 'Introduction to Ayurveda: doshas, daily routines, and basic herbs.',
    difficulty: 'Beginner',
    xp_reward: 100,
    category: 'Ayurveda',
    estimated_time: '15m',
    hero_story: 'Balance begins with daily practice.',
  },
  {
    slug: 'sustainable-farming',
    title: 'Sustainable Farming',
    description: 'Traditional sustainable farming practices and companion planting.',
    difficulty: 'Intermediate',
    xp_reward: 150,
    category: 'Farming',
    estimated_time: '25m',
    hero_story: 'Farm with the seasons, not against them.',
  },
  {
    slug: 'vedic-mathematics',
    title: 'Vedic Mathematics',
    description: 'Shortcuts and patterns for fast mental calculation from Vedic tradition.',
    difficulty: 'Beginner',
    xp_reward: 120,
    category: 'Mathematics',
    estimated_time: '20m',
    hero_story: 'Speed comes from pattern, not pressure.',
  },
  {
    slug: 'herbal-medicine',
    title: 'Herbal Medicine',
    description: 'The healing properties of native flora and roots.',
    difficulty: 'Intermediate',
    xp_reward: 450,
    category: 'Medicine',
    estimated_time: '3h',
    hero_story: 'The village pharmacy in a single tree.',
  },
  {
    slug: 'traditional-farming',
    title: 'Traditional Farming',
    description: 'Sustainable agriculture practices based on ancient rhythms.',
    difficulty: 'Beginner',
    xp_reward: 500,
    category: 'Agriculture',
    estimated_time: '2h',
    hero_story: 'Land, water, and seasons in balance.',
  },
  {
    slug: 'ancient-water-conservation',
    title: 'Ancient Water Conservation',
    description: 'Stepwells, rainwater harvesting, and desert survival.',
    difficulty: 'Intermediate',
    xp_reward: 600,
    category: 'Engineering',
    estimated_time: '4h',
    hero_story: 'When the monsoon came, the villages were ready.',
  },
  {
    slug: 'folk-stories-morals',
    title: 'Folk Stories & Morals',
    description: 'Oral traditions passed down generations for moral education.',
    difficulty: 'Beginner',
    xp_reward: 300,
    category: 'Culture',
    estimated_time: '1h',
    hero_story: 'Memory carried by the voice of the elders.',
  },
  {
    slug: 'traditional-crafts',
    title: 'Traditional Crafts',
    description: 'Pottery, weaving, and sustainable material crafting.',
    difficulty: 'Advanced',
    xp_reward: 700,
    category: 'Arts',
    estimated_time: '5h',
    hero_story: 'Craft as inheritance, not decoration.',
  },
  {
    slug: 'astronomy-navigation',
    title: 'Astronomy & Navigation',
    description: 'Reading the stars without modern instruments.',
    difficulty: 'Advanced',
    xp_reward: 800,
    category: 'Science',
    estimated_time: '4h',
    hero_story: 'The sky as a map and a calendar.',
  },
]

export const seedLessons = [
  {
    moduleSlug: 'ayurveda-basics',
    title: 'Understanding the Doshas',
    content: 'Vata, Pitta, and Kapha describe different balances of energy, movement, heat, and stability.',
    order_index: 1,
  },
  {
    moduleSlug: 'ayurveda-basics',
    title: 'Dinacharya and Routine',
    content: 'A steady daily rhythm helps support digestion, sleep, and mental clarity.',
    order_index: 2,
  },
  {
    moduleSlug: 'ayurveda-basics',
    title: 'Simple Herbs',
    content: 'Tulsi, ginger, and turmeric are often used in household remedies and teas.',
    order_index: 3,
  },
  {
    moduleSlug: 'ayurveda-basics',
    title: 'Assessment',
    content: 'Review the three doshas and the role of daily routine in well-being.',
    order_index: 4,
  },
  {
    moduleSlug: 'sustainable-farming',
    title: 'Crop Rotation',
    content: 'Rotating crops helps preserve soil nutrients and reduce pest pressure.',
    order_index: 1,
  },
  {
    moduleSlug: 'sustainable-farming',
    title: 'Companion Planting',
    content: 'Certain plants support each other by improving shade, soil, or pest control.',
    order_index: 2,
  },
  {
    moduleSlug: 'sustainable-farming',
    title: 'Organic Inputs',
    content: 'Compost and natural mulch improve moisture retention and soil life.',
    order_index: 3,
  },
  {
    moduleSlug: 'sustainable-farming',
    title: 'Assessment',
    content: 'Apply sustainable farming ideas to a small field or garden.',
    order_index: 4,
  },
  {
    moduleSlug: 'vedic-mathematics',
    title: 'Base Patterns',
    content: 'Vedic methods simplify numbers by looking for useful patterns and complements.',
    order_index: 1,
  },
  {
    moduleSlug: 'vedic-mathematics',
    title: 'Rapid Multiplication',
    content: 'Shortcuts can reduce the steps needed for common multiplication problems.',
    order_index: 2,
  },
  {
    moduleSlug: 'vedic-mathematics',
    title: 'Mental Practice',
    content: 'Consistent practice improves speed, accuracy, and confidence in calculation.',
    order_index: 3,
  },
  {
    moduleSlug: 'vedic-mathematics',
    title: 'Assessment',
    content: 'Use a pattern or shortcut to solve a simple arithmetic problem.',
    order_index: 4,
  },
  {
    moduleSlug: 'herbal-medicine',
    title: 'Introduction to Neem',
    content: 'Neem is a traditional medicinal tree used for skin, immunity, and oral health.',
    order_index: 1,
  },
  {
    moduleSlug: 'herbal-medicine',
    title: 'Preparing Herbal Remedies',
    content: 'Leaves, roots, and bark are prepared carefully by drying, boiling, or grinding them into simple remedies.',
    order_index: 2,
  },
  {
    moduleSlug: 'herbal-medicine',
    title: 'Using Herbs Safely',
    content: 'Traditional medicine emphasizes moderation, correct dosage, and consulting local knowledge holders.',
    order_index: 3,
  },
  {
    moduleSlug: 'herbal-medicine',
    title: 'Final Assessment',
    content: 'Review the uses, preparation, and precautions of neem remedies.',
    order_index: 4,
  },
  {
    moduleSlug: 'traditional-farming',
    title: 'Seasonal Cropping',
    content: 'Ancient systems aligned crops with rainfall and soil cycles.',
    order_index: 1,
  },
  {
    moduleSlug: 'traditional-farming',
    title: 'Composting and Soil Health',
    content: 'Farmers used organic waste to restore fertility over time.',
    order_index: 2,
  },
  {
    moduleSlug: 'traditional-farming',
    title: 'Seed Saving',
    content: 'Seed selection preserved resilience across generations.',
    order_index: 3,
  },
  {
    moduleSlug: 'traditional-farming',
    title: 'Assessment',
    content: 'Apply the principles of regenerative farming in local contexts.',
    order_index: 4,
  },
  {
    moduleSlug: 'ancient-water-conservation',
    title: 'Reading the Stepwell',
    content: 'Stepwells stored rainwater and cooled villages during dry months.',
    order_index: 1,
  },
  {
    moduleSlug: 'ancient-water-conservation',
    title: 'Rainwater Harvesting',
    content: 'Catchment design and tanks turned seasonal rain into year-round supply.',
    order_index: 2,
  },
  {
    moduleSlug: 'ancient-water-conservation',
    title: 'Water Sharing Rules',
    content: 'Communities set customs to distribute water fairly during drought.',
    order_index: 3,
  },
  {
    moduleSlug: 'ancient-water-conservation',
    title: 'Assessment',
    content: 'Compare ancient water systems with modern conservation practices.',
    order_index: 4,
  },
  {
    moduleSlug: 'folk-stories-morals',
    title: 'Why Stories Teach',
    content: 'Stories carry values, memory, and practical wisdom from one generation to the next.',
    order_index: 1,
  },
  {
    moduleSlug: 'folk-stories-morals',
    title: 'Listening to Elders',
    content: 'Oral traditions preserve language, identity, and community guidance.',
    order_index: 2,
  },
  {
    moduleSlug: 'folk-stories-morals',
    title: 'Moral Reflection',
    content: 'Each tale invites the learner to think about kindness, courage, and responsibility.',
    order_index: 3,
  },
  {
    moduleSlug: 'folk-stories-morals',
    title: 'Assessment',
    content: 'Reflect on the lesson and identify the moral of a traditional story.',
    order_index: 4,
  },
  {
    moduleSlug: 'traditional-crafts',
    title: 'Materials and Tools',
    content: 'Crafts begin with local clay, fiber, wood, and natural dyes.',
    order_index: 1,
  },
  {
    moduleSlug: 'traditional-crafts',
    title: 'Pattern and Patience',
    content: 'Weaving and pottery reward careful repetition and attention to form.',
    order_index: 2,
  },
  {
    moduleSlug: 'traditional-crafts',
    title: 'Finishing and Preservation',
    content: 'Natural finishes protect handcrafted objects while keeping them functional.',
    order_index: 3,
  },
  {
    moduleSlug: 'traditional-crafts',
    title: 'Assessment',
    content: 'Match the right material and technique to the craft being made.',
    order_index: 4,
  },
  {
    moduleSlug: 'astronomy-navigation',
    title: 'Finding Direction by Stars',
    content: 'Travelers used star positions to orient themselves after sunset.',
    order_index: 1,
  },
  {
    moduleSlug: 'astronomy-navigation',
    title: 'Seasonal Sky Patterns',
    content: 'The night sky helped communities predict seasons and plan travel.',
    order_index: 2,
  },
  {
    moduleSlug: 'astronomy-navigation',
    title: 'Navigation Without Instruments',
    content: 'Landmarks, stars, and memory worked together for safe journeys.',
    order_index: 3,
  },
  {
    moduleSlug: 'astronomy-navigation',
    title: 'Assessment',
    content: 'Use the stars and the horizon to describe a simple navigation route.',
    order_index: 2,
  },
]

export const seedQuizzes = [
  {
    moduleSlug: 'ayurveda-basics',
    title: 'Ayurveda Basics Quiz',
    passing_score: 70,
  },
  {
    moduleSlug: 'sustainable-farming',
    title: 'Sustainable Farming Quiz',
    passing_score: 70,
  },
  {
    moduleSlug: 'vedic-mathematics',
    title: 'Vedic Mathematics Quiz',
    passing_score: 70,
  },
  {
    moduleSlug: 'herbal-medicine',
    title: 'Herbal Medicine Basics',
    passing_score: 70,
  },
  {
    moduleSlug: 'traditional-farming',
    title: 'Farming Foundations',
    passing_score: 70,
  },
  {
    moduleSlug: 'ancient-water-conservation',
    title: 'Water Wisdom',
    passing_score: 70,
  },
  {
    moduleSlug: 'folk-stories-morals',
    title: 'Story Keeper Quiz',
    passing_score: 70,
  },
  {
    moduleSlug: 'traditional-crafts',
    title: 'Craft and Technique',
    passing_score: 70,
  },
  {
    moduleSlug: 'astronomy-navigation',
    title: 'Sky Navigation',
    passing_score: 70,
  },
]

export const seedQuizQuestions = [
  {
    quizTitle: 'Ayurveda Basics Quiz',
    question: 'Which concept describes the three energy types in Ayurveda?',
    options: ['Doshas', 'Mantras', 'Stupas', 'Glyphs'],
    correct_answer: 'Doshas',
    order_index: 1,
  },
  {
    quizTitle: 'Ayurveda Basics Quiz',
    question: 'What is dinacharya?',
    options: ['Daily routine', 'A cooking pot', 'A dance step', 'A farming tool'],
    correct_answer: 'Daily routine',
    order_index: 2,
  },
  {
    quizTitle: 'Sustainable Farming Quiz',
    question: 'Why is crop rotation useful?',
    options: ['It helps preserve soil nutrients', 'It removes all seeds', 'It stops rainfall', 'It makes tractors faster'],
    correct_answer: 'It helps preserve soil nutrients',
    order_index: 1,
  },
  {
    quizTitle: 'Sustainable Farming Quiz',
    question: 'What is one benefit of compost?',
    options: ['Improves soil life', 'Kills all insects instantly', 'Turns water into oil', 'Makes plants grow in the dark'],
    correct_answer: 'Improves soil life',
    order_index: 2,
  },
  {
    quizTitle: 'Vedic Mathematics Quiz',
    question: 'What does Vedic mathematics often rely on?',
    options: ['Patterns and shortcuts', 'Only calculators', 'Guessing randomly', 'Measuring in meters'],
    correct_answer: 'Patterns and shortcuts',
    order_index: 1,
  },
  {
    quizTitle: 'Vedic Mathematics Quiz',
    question: 'What improves mental calculation speed?',
    options: ['Practice', 'Avoiding numbers', 'Ignoring methods', 'Counting on fingers only'],
    correct_answer: 'Practice',
    order_index: 2,
  },
  {
    quizTitle: 'Herbal Medicine Basics',
    question: 'Which ingredient improves curcumin absorption?',
    options: ['Black pepper', 'Salt', 'Rice', 'Lemon'],
    correct_answer: 'Black pepper',
    order_index: 1,
  },
  {
    quizTitle: 'Herbal Medicine Basics',
    question: 'What is a common use of neem?',
    options: ['Skin care', 'Metal polishing', 'Painting walls', 'Fuel only'],
    correct_answer: 'Skin care',
    order_index: 2,
  },
  {
    quizTitle: 'Farming Foundations',
    question: 'Why was seasonal cropping important?',
    options: ['It ignored rainfall', 'It matched climate cycles', 'It needed more chemicals', 'It reduced biodiversity'],
    correct_answer: 'It matched climate cycles',
    order_index: 1,
  },
  {
    quizTitle: 'Farming Foundations',
    question: 'What does composting improve?',
    options: ['Soil fertility', 'Plastic production', 'Phone battery life', 'Concrete strength'],
    correct_answer: 'Soil fertility',
    order_index: 2,
  },
  {
    quizTitle: 'Water Wisdom',
    question: 'What was a key purpose of stepwells?',
    options: ['Stored rainwater', 'Generated electricity', 'Made bricks', 'Counted stars'],
    correct_answer: 'Stored rainwater',
    order_index: 1,
  },
  {
    quizTitle: 'Water Wisdom',
    question: 'Why were water-sharing customs important?',
    options: ['They prevented unfair access', 'They stopped rainfall', 'They made water salty', 'They replaced wells'],
    correct_answer: 'They prevented unfair access',
    order_index: 2,
  },
  {
    quizTitle: 'Story Keeper Quiz',
    question: 'What do folk stories usually preserve?',
    options: ['Only facts', 'Values and memory', 'Metal tools', 'Weather maps'],
    correct_answer: 'Values and memory',
    order_index: 1,
  },
  {
    quizTitle: 'Story Keeper Quiz',
    question: 'Who often carries oral traditions forward?',
    options: ['Elders', 'Engineers', 'Astronauts', 'Pilots'],
    correct_answer: 'Elders',
    order_index: 2,
  },
  {
    quizTitle: 'Craft and Technique',
    question: 'Which material is commonly used in traditional pottery?',
    options: ['Clay', 'Glass', 'Plastic', 'Rubber'],
    correct_answer: 'Clay',
    order_index: 1,
  },
  {
    quizTitle: 'Craft and Technique',
    question: 'Why is patience important in craft?',
    options: ['It improves accuracy', 'It removes all tools', 'It makes work invisible', 'It reduces materials to nothing'],
    correct_answer: 'It improves accuracy',
    order_index: 2,
  },
  {
    quizTitle: 'Sky Navigation',
    question: 'What helped travelers orient themselves at night?',
    options: ['Star positions', 'Paper maps only', 'Televisions', 'Factory lights'],
    correct_answer: 'Star positions',
    order_index: 1,
  },
  {
    quizTitle: 'Sky Navigation',
    question: 'Why did communities study seasonal sky patterns?',
    options: ['To predict seasons', 'To grow metal', 'To reduce daylight', 'To paint roads'],
    correct_answer: 'To predict seasons',
    order_index: 2,
  },
]

export const seedAchievements = [
  {
    slug: 'first-harvest',
    title: 'First Harvest',
    description: 'Complete your first agricultural lesson.',
    xp_reward: 100,
  },
  {
    slug: 'village-elder',
    title: 'Village Elder',
    description: 'Reach level 10 and guide others.',
    xp_reward: 250,
  },
  {
    slug: 'healer-apprentice',
    title: 'Healer Apprentice',
    description: 'Master the basics of herbal medicine.',
    xp_reward: 150,
  },
  {
    slug: 'water-saver',
    title: 'Water Saver',
    description: 'Learn about ancient stepwells.',
    xp_reward: 150,
  },
]

export const seedUsers = [
  {
    name: 'Sita Devi',
    email: 'sita@tradition.dev',
    password: 'Password123!',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150',
    xp_points: 12500,
    level: 25,
    streak: 31,
  },
  {
    name: 'Ravi Kumar',
    email: 'ravi@tradition.dev',
    password: 'Password123!',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150',
    xp_points: 11200,
    level: 23,
    streak: 22,
  },
  {
    name: 'Priya Sharma',
    email: 'priya@tradition.dev',
    password: 'Password123!',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    xp_points: 10800,
    level: 22,
    streak: 28,
  },
  {
    name: 'Arjun Singh',
    email: 'arjun@tradition.dev',
    password: 'Password123!',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    xp_points: 9500,
    level: 20,
    streak: 17,
  },
  {
    name: 'Anand Traveler',
    email: 'anand@tradition.dev',
    password: 'Password123!',
    avatar_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=150',
    xp_points: 2450,
    level: 5,
    streak: 12,
  },
]