export const quizQuestions = [
  {
    quiz_slug: 'folk-lore-quiz',
    question: 'What happened after the sacred grove was destroyed?',
    options: [
      'The village became richer',
      'The birds went silent',
      'More trees grew',
      'Nothing changed',
    ],
    correct_answer: 'The birds went silent',
    order_index: 1,
  },
  {
    quiz_slug: 'folk-lore-quiz',
    question: 'What lesson does the Lamp of Listening teach?',
    options: [
      'Speed is everything',
      'Patience and listening are important',
      'Money solves all problems',
      'Nature should be ignored',
    ],
    correct_answer: 'Patience and listening are important',
    order_index: 2,
  },
  {
    quiz_slug: 'folk-lore-quiz',
    question: 'Why did the weaver refuse to rush the veil?',
    options: [
      'He was lazy',
      'Beauty requires patience and soul',
      'He hated the girl',
      'He lacked silk',
    ],
    correct_answer: 'Beauty requires patience and soul',
    order_index: 3,
  },
  {
    quiz_slug: 'folk-lore-quiz',
    question: 'What healed the relationship between the brothers?',
    options: [
      'Money',
      'A larger farm',
      'Forgiveness and kindness',
      'Silence',
    ],
    correct_answer: 'Forgiveness and kindness',
    order_index: 4,
  },
  {
    quiz_slug: 'herbal-wisdom-quiz',
    question: 'What did the Mother of Green believe health meant?',
    options: [
      'Absence of pain',
      'Harmony between body and soul',
      'Physical strength only',
      'Using machines',
    ],
    correct_answer: 'Harmony between body and soul',
    order_index: 1,
  },
  {
    quiz_slug: 'herbal-wisdom-quiz',
    question: 'What lesson did the healer\'s son learn?',
    options: [
      'Forests are useless',
      'Nature should be respected',
      'Money is most important',
      'Science is bad',
    ],
    correct_answer: 'Nature should be respected',
    order_index: 2,
  },
  {
    quiz_slug: 'herbal-wisdom-quiz',
    question: 'Why did the merchant\'s son begin recovering?',
    options: [
      'Because of expensive machines',
      'Because of emotional and herbal healing',
      'Because of surgery',
      'Because of isolation',
    ],
    correct_answer: 'Because of emotional and herbal healing',
    order_index: 3,
  },
  {
    quiz_slug: 'herbal-wisdom-quiz',
    question: 'What did the king ultimately learn?',
    options: [
      'Youth is eternal',
      'True strength comes from inner balance',
      'Science solves everything',
      'Nature should be controlled',
    ],
    correct_answer: 'True strength comes from inner balance',
    order_index: 4,
  },
  {
    quiz_slug: 'traditional-farming-quiz',
    question: 'Why did the father\'s crops survive the drought?',
    options: [
      'He used more chemicals',
      'He had deeper wells',
      'Traditional farming preserved soil health',
      'He planted fewer crops',
    ],
    correct_answer: 'Traditional farming preserved soil health',
    order_index: 1,
  },
  {
    quiz_slug: 'traditional-farming-quiz',
    question: 'What is the moral of The Gold of the Earth?',
    options: [
      'Fast farming is best',
      'Traditional farming protects life and soil',
      'Machines are harmful',
      'Wealth is more important than nature',
    ],
    correct_answer: 'Traditional farming protects life and soil',
    order_index: 2,
  },
] as const
